version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:5432 --timeout=30 --
             python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py populate_data &&
             gunicorn --bind 0.0.0.0:8000 HoliFund.wsgi:application"
    volumes:
      - .:/code
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DATABASE_URL=postgres://postgres:@db:5432/postgres
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
